name: push-on-main
on:
  push:
    branch:
      - main
jobs:
  deploy:
    name: Deploy to EC2 
    runs-on: ubuntu-latest
    steps:
    - name: File Checkout
      uses: actions/checkout@v4

    - name: Copy files with SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "./"
        REMOTE_HOST: "ec2-54-173-125-111.compute-1.amazonaws.com" 
        REMOTE_USER: "ubuntu"
        TARGET: "/var/www/html/deploy-actions"
        EXCLUDE: "/dist/, /vendor/, /node_modules/, **.env"
